/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pencatatan_tc_app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class e_pemasukan extends javax.swing.JFrame {

    /**
     * Creates new form e_pemasukan
     */
    public e_pemasukan() {
        initComponents();
        load_table();
        loadNamaSupir();  // Memuat nama supir ke JComboBox
        loadPlatTruck();
    }
    
    private void kosong(){
        noinv1.setText(null);
        date1.setDate(null);
        nama_supir1.setSelectedItem(null);
        plat_truck1.setSelectedItem(null);
        pelanggan1.setText(null);
        pekerjaan1.setText(null);
        lokasi1.setText(null);
        total_jam1.setText(null);
        harga1.setText(null);
        status1.setSelectedItem(null);
}
    
    private void load_table() {
    // Membuat tampilan model tabel
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("No Invoice");
    model.addColumn("Tanggal");
    model.addColumn("Nama");
    model.addColumn("Plat Truk");
    model.addColumn("Pelanggan");
    model.addColumn("Pekerjaan");
    model.addColumn("Lokasi");
    model.addColumn("Total Jam");
    model.addColumn("Harga");
    model.addColumn("Status");

    try {
        int no = 1;
        String sql = "SELECT ptc.no_invoice, ptc.tanggal, s.nama, tc.plat_truck, ptc.pelanggan, "
                   + "ptc.pekerjaan, ptc.lokasi, ptc.total_jam, ptc.harga, ptc.status "
                   + "FROM tb_pencatatan_truck_crane ptc "
                   + "JOIN tb_supir s ON ptc.id_supir = s.id_supir "
                   + "JOIN tb_truck_crane tc ON ptc.id_truck_crane = tc.id_truck_crane";
        java.sql.Connection conn = (Connection) koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                no++,
                res.getString("no_invoice"),
                res.getString("tanggal"),
                res.getString("nama"),
                res.getString("plat_truck"),
                res.getString("pelanggan"),
                res.getString("pekerjaan"),
                res.getString("lokasi"),
                res.getString("total_jam"),
                res.getString("harga"),
                res.getString("status")
            });
        }
        Jtbldata.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    
    private void loadNamaSupir() {
    try (Connection conn = koneksi.configDB()) {
        String query = "SELECT nama FROM tb_supir";
        PreparedStatement stmt = conn.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();
        
        nama_supir1.removeAllItems(); // Bersihkan item yang ada sebelumnya
        while (rs.next()) {
            nama_supir1.addItem(rs.getString("nama")); // Tambahkan nama supir ke JComboBox
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat nama supir: " + e.getMessage());
    }
}

    
    private void loadPlatTruck() {
    try (Connection conn = koneksi.configDB()) {
        String query = "SELECT plat_truck FROM tb_truck_crane";
        PreparedStatement stmt = conn.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();
        
        plat_truck1.removeAllItems(); // Bersihkan item yang ada sebelumnya
        while (rs.next()) {
            plat_truck1.addItem(rs.getString("plat_truck")); // Tambahkan plat truk ke JComboBox
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat plat truk: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtbldata = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        status1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        nama_supir1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        total_jam1 = new javax.swing.JTextField();
        lokasi1 = new javax.swing.JTextField();
        harga1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pelanggan1 = new javax.swing.JTextField();
        plat_truck1 = new javax.swing.JComboBox<>();
        noinv1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pekerjaan1 = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("EDIT PEMASUKAN");

        Jtbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Jtbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtbldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtbldata);

        jLabel2.setText("No Invoice :");

        jLabel8.setText("Lokasi :");

        jLabel9.setText("Total Jam :");

        status1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Term", "Lunas" }));

        jLabel10.setText("Harga :");

        nama_supir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_supir1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Status :");

        lokasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasi1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal :");

        jLabel4.setText("Nama Supir :");

        jLabel5.setText("Plat Truk :");

        jLabel6.setText("Pelanggan :");

        jLabel7.setText("Pekerjaan :");

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        jMenuItem1.setText("Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Pemasukan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Tambah Pemasukan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(419, 419, 419)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noinv1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pekerjaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pelanggan1)
                                    .addComponent(plat_truck1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nama_supir1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23)
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total_jam1)
                            .addComponent(lokasi1)
                            .addComponent(harga1)
                            .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(btnedit)
                .addGap(81, 81, 81)
                .addComponent(btnhapus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noinv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(pekerjaan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(nama_supir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(plat_truck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(pelanggan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lokasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(total_jam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(harga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnedit)
                    .addComponent(btnhapus))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtbldataMouseClicked
// Mendapatkan baris yang diklik
int baris = Jtbldata.rowAtPoint(evt.getPoint());

// Mendapatkan data dari setiap kolom pada baris yang diklik
String noInvoice = Jtbldata.getValueAt(baris, 1).toString();
noinv1.setText(noInvoice);

String tanggal = Jtbldata.getValueAt(baris, 2).toString();
try {
    java.util.Date dateValue = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
    date1.setDate(dateValue);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Tanggal tidak valid");
}

String namaSupir = Jtbldata.getValueAt(baris, 3).toString();
nama_supir1.setSelectedItem(namaSupir);

String platTruck = Jtbldata.getValueAt(baris, 4).toString();
plat_truck1.setSelectedItem(platTruck);

String pelangganValue = Jtbldata.getValueAt(baris, 5).toString();
pelanggan1.setText(pelangganValue);

String pekerjaanValue = Jtbldata.getValueAt(baris, 6).toString();
pekerjaan1.setText(pekerjaanValue);

String lokasiValue = Jtbldata.getValueAt(baris, 7).toString();
lokasi1.setText(lokasiValue);

String totalJam = Jtbldata.getValueAt(baris, 8).toString();
total_jam1.setText(totalJam);

String hargaValue = Jtbldata.getValueAt(baris, 9).toString();
harga1.setText(hargaValue);

String statusValue = Jtbldata.getValueAt(baris, 10).toString();
status1.setSelectedItem(statusValue);


    }//GEN-LAST:event_JtbldataMouseClicked

    private void lokasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lokasi1ActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
       try {
    // Create SQL query for updating data in the tb_pencatatan_truck_crane table
    String sql = "UPDATE tb_pencatatan_truck_crane SET "
            + "tanggal = ?, "
            + "id_supir = (SELECT id_supir FROM tb_supir WHERE nama = ? LIMIT 1), "
            + "id_truck_crane = (SELECT id_truck_crane FROM tb_truck_crane WHERE plat_truck = ? LIMIT 1), "
            + "pelanggan = ?, "
            + "pekerjaan = ?, "
            + "lokasi = ?, "
            + "total_jam = ?, "
            + "harga = ?, "
            + "status = ? "
            + "WHERE no_invoice = ?";

    // Establish a connection to the database
    try (Connection conn = (Connection) koneksi.configDB();
         PreparedStatement pst = conn.prepareStatement(sql)) {

        // Set the values in the prepared statement from the form fields
        pst.setDate(1, new java.sql.Date(date1.getDate().getTime()));
        pst.setString(2, nama_supir1.getSelectedItem().toString());
        pst.setString(3, plat_truck1.getSelectedItem().toString());
        pst.setString(4, pelanggan1.getText());
        pst.setString(5, pekerjaan1.getText());
        pst.setString(6, lokasi1.getText());
        pst.setString(7, total_jam1.getText());
        pst.setString(8, harga1.getText());
        pst.setString(9, status1.getSelectedItem().toString());
        pst.setString(10, noinv1.getText());

        // Execute the update
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil diedit");

    } catch (SQLException e) {
        // Handle any SQL exceptions
        JOptionPane.showMessageDialog(null, "Perubahan data gagal: " + e.getMessage());
    }

    // Reload the table and clear the form
    load_table();
    kosong();

} catch (Exception e) {
    // Handle general exceptions
    JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage());
}


    }//GEN-LAST:event_btneditActionPerformed

    private void nama_supir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_supir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_supir1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        new dashboard().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        new pemasukan().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        new t_pemasukan().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try{
            String sql = "delete from tb_pencatatan_truck_crane WHERE no_invoice='"+noinv1.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(e_pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(e_pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(e_pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(e_pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new e_pemasukan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtbldata;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JTextField harga1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lokasi1;
    private javax.swing.JComboBox<String> nama_supir1;
    private javax.swing.JTextField noinv1;
    private javax.swing.JTextField pekerjaan1;
    private javax.swing.JTextField pelanggan1;
    private javax.swing.JComboBox<String> plat_truck1;
    private javax.swing.JComboBox<String> status1;
    private javax.swing.JTextField total_jam1;
    // End of variables declaration//GEN-END:variables
}
